# 11. 딥러닝 레이어의 이해(2) Embedding, Recurrent

## 11-3. 단어를 부탁해! Embedding 레이어

https://www.baeldung.com/cs/svm-vs-perceptron#perceptron

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
some_words = tf.constant([[3, 57, 35]])
# 3번 단어 / 57번 단어 / 35번 단어로 이루어진 한 문장입니다.

print("Embedding을 진행할 문장:", some_words.shape)
embedding_layer = tf.keras.layers.Embedding(input_dim=64, output_dim=100)
# 총 64개의 단어를 포함한 Embedding 레이어를 선언할 것이고,
# 각 단어는 100차원으로 분산 표현 할 것입니다.

print("Embedding된 문장:", embedding_layer(some_words).shape)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)
some_words.shape


Embedding을 진행할 문장: (1, 3)
Embedding된 문장: (1, 3, 100)
Embedding Layer의 Weight 형태: (64, 100)


TensorShape([1, 3])

In [3]:
vocab = {      # 사용할 단어 사전 정의
    "i": 0,
    "need": 1,
    "some": 2,
    "more": 3,
    "coffee": 4,
    "cake": 5,
    "cat": 6,
    "dog": 7
}

sentence = "i i i i need some more coffee coffee coffee"
# 위 sentence
_input = [vocab[w] for w in sentence.split()]  # [0, 0, 0, 0, 1, 2, 3, 4, 4, 4]

vocab_size = len(vocab)   # 8

one_hot = tf.one_hot(_input, vocab_size)
print(one_hot.numpy())    # 원-핫 인코딩 벡터를 출력해 봅시다.


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


dist = np.linalg.norm(point1 - point2)

In [4]:
a = one_hot.numpy()[0]
b = one_hot.numpy()[2]
dist = np.linalg.norm(a-b)
dist

0.0

In [5]:
distribution_size = 2   # 보기 좋게 2차원으로 분산 표현하도록 하죠!
linear = tf.keras.layers.Dense(units=distribution_size, use_bias=False)
one_hot_linear = linear(one_hot)  # pne_hot vector의 inner product(dot product) return

print("Linear Weight")
print(linear.weights[0].numpy())

print("\nOne-Hot Linear Result")
print(one_hot_linear.numpy())
type(one_hot_linear)

Linear Weight
[[ 0.3257364  -0.05448061]
 [-0.6363881  -0.5397369 ]
 [ 0.05254245  0.23338008]
 [-0.22760797 -0.6594147 ]
 [-0.6330251   0.6086302 ]
 [-0.03304338  0.6176152 ]
 [ 0.3513745   0.6153393 ]
 [-0.65077806 -0.28070095]]

One-Hot Linear Result
[[ 0.3257364  -0.05448061]
 [ 0.3257364  -0.05448061]
 [ 0.3257364  -0.05448061]
 [ 0.3257364  -0.05448061]
 [-0.6363881  -0.5397369 ]
 [ 0.05254245  0.23338008]
 [-0.22760797 -0.6594147 ]
 [-0.6330251   0.6086302 ]
 [-0.6330251   0.6086302 ]
 [-0.6330251   0.6086302 ]]


tensorflow.python.framework.ops.EagerTensor

In [6]:
some_words

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 3, 57, 35]], dtype=int32)>

In [7]:
some_words = tf.constant([_input])
print("Embedding을 진행할 문장:", some_words.shape)

# 총 64개의 단어를 포함한 Embedding 레이어를 선언할 것이고,
# 각 단어는 100차원으로 분산 표현 할 것입니다.
embedding_layer = tf.keras.layers.Embedding(input_dim=64, output_dim=100)

print("Embedding된 문장:", embedding_layer(some_words).shape)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)

embedding_layer(some_words)

Embedding을 진행할 문장: (1, 10)
Embedding된 문장: (1, 10, 100)
Embedding Layer의 Weight 형태: (64, 100)


<tf.Tensor: shape=(1, 10, 100), dtype=float32, numpy=
array([[[ 1.59037225e-02, -4.39367294e-02, -4.19992693e-02,
          1.62905194e-02, -4.89874966e-02, -3.55794281e-03,
          2.39191204e-03,  3.03274430e-02,  1.77160986e-02,
         -4.57770117e-02, -4.33978438e-02,  4.31905873e-02,
         -4.66997996e-02, -3.65551934e-02,  2.56889202e-02,
          4.75686081e-02, -2.20721848e-02, -2.51235366e-02,
         -2.31356509e-02, -4.59744707e-02, -2.95577180e-02,
         -3.28500755e-02, -1.91364884e-02, -2.02991068e-04,
         -3.92551348e-03,  5.93448803e-03,  4.56021540e-02,
         -3.01446561e-02, -3.30506787e-02,  9.83383507e-03,
          4.01899554e-02,  3.11869122e-02,  4.53810766e-03,
         -3.14761549e-02, -6.35179132e-03,  3.75124253e-02,
         -1.11296996e-02,  4.59141992e-02,  2.42453255e-02,
          1.52401663e-02,  8.65340233e-03, -2.81138550e-02,
         -2.53296141e-02, -3.30880657e-02,  9.44806263e-03,
         -4.01143804e-02, -2.85150763e-02,  4.

In [8]:
some_words = tf.constant([[3, 57, 35]])
# 3번 단어 / 57번 단어 / 35번 단어로 이루어진 한 문장입니다.

print("Embedding을 진행할 문장:", some_words.shape)
embedding_layer = tf.keras.layers.Embedding(input_dim=64, output_dim=100)
# 총 64개의 단어를 포함한 Embedding 레이어를 선언할 것이고,
# 각 단어는 100차원으로 분산 표현 할 것입니다.

print("Embedding된 문장:", embedding_layer(some_words).shape)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)
some_words.shape


Embedding을 진행할 문장: (1, 3)
Embedding된 문장: (1, 3, 100)
Embedding Layer의 Weight 형태: (64, 100)


TensorShape([1, 3])

## 11-4. 순차적인 데이터! Recurrent 레이어 (1) RNN

In [9]:
sentence = "What time is it ?"
dic = {
    "is": 0,
    "it": 1,
    "What": 2,
    "time": 3,
    "?": 4
}

print("RNN에 입력할 문장:", sentence)

sentence_tensor = tf.constant([[dic[word] for word in sentence.split()]])

print("Embedding을 위해 단어 매핑:", sentence_tensor.numpy())
print("입력 문장 데이터 형태:", sentence_tensor.shape)

embedding_layer = tf.keras.layers.Embedding(input_dim=len(dic), output_dim=100)
emb_out = embedding_layer(sentence_tensor)

print("\nEmbedding 결과:", emb_out.shape)
print("Embedding Layer의 Weight 형태:", embedding_layer.weights[0].shape)

rnn_seq_layer = \
tf.keras.layers.SimpleRNN(units=64, return_sequences=True, use_bias=False)
rnn_seq_out = rnn_seq_layer(emb_out)

print("\nRNN 결과 (모든 Step Output):", rnn_seq_out.shape)
print("RNN Layer의 Weight 형태:", rnn_seq_layer.weights[0].shape)

rnn_fin_layer = tf.keras.layers.SimpleRNN(units=64, use_bias=False)
rnn_fin_out = rnn_fin_layer(emb_out)

print("\nRNN 결과 (최종 Step Output):", rnn_fin_out.shape)
print("RNN Layer의 Weight 형태:", rnn_fin_layer.weights[0].shape)

RNN에 입력할 문장: What time is it ?
Embedding을 위해 단어 매핑: [[2 3 0 1 4]]
입력 문장 데이터 형태: (1, 5)

Embedding 결과: (1, 5, 100)
Embedding Layer의 Weight 형태: (5, 100)

RNN 결과 (모든 Step Output): (1, 5, 64)
RNN Layer의 Weight 형태: (100, 64)

RNN 결과 (최종 Step Output): (1, 64)
RNN Layer의 Weight 형태: (100, 64)


In [10]:
lstm_seq_layer = tf.keras.layers.LSTM(units=64, return_sequences=True, use_bias=False)
lstm_seq_out = lstm_seq_layer(emb_out)

print("\nLSTM 결과 (모든 Step Output):", lstm_seq_out.shape)
print("LSTM Layer의 Weight 형태:", lstm_seq_layer.weights[0].shape)

lstm_fin_layer = tf.keras.layers.LSTM(units=64, use_bias=False)
lstm_fin_out = lstm_fin_layer(emb_out)

print("\nLSTM 결과 (최종 Step Output):", lstm_fin_out.shape)
print("LSTM Layer의 Weight 형태:", lstm_fin_layer.weights[0].shape)


LSTM 결과 (모든 Step Output): (1, 5, 64)
LSTM Layer의 Weight 형태: (100, 256)

LSTM 결과 (최종 Step Output): (1, 64)
LSTM Layer의 Weight 형태: (100, 256)
